#!/usr/bin/env node
import { execSync } from 'child_process';
import process from 'process';

function run(command, ignoreError = false) {
  try {
    console.log(`Running: ${command}`);
    execSync(command, { stdio: 'inherit' });
    return true;
  } catch (error) {
    if (!ignoreError) {
      console.error(`Command failed: ${command}`);
    }
    return false;
  }
}

function checkState() {
  try {
    execSync('./scripts/healthcheck.mjs', { stdio: 'pipe' });

    // Check diff ignoring log files generated by the workflow
    const diff = execSync('git status --porcelain | grep -v "\.log$" || true', { stdio: 'pipe' }).toString().trim();
    if (diff !== '') {
      console.log('System healthy and fixes generated. Exiting 0.');
      process.exit(0);
    }
  } catch (e) {
    // Healthcheck failed, continue to next repair step
  }
}

console.log('Starting auto-repair sequence...');

// Step 1: Rebuild/reinstall
run('npm ci');
checkState();

// Step 2: Lint/format auto-fix
run('npx eslint . --fix', true);
checkState();

// Step 3: Snapshot/generated updates
run('npx vitest run -u', true);
checkState();

// Step 4: Type stubs/analyzer config
run('npx typesync --yes', true);
checkState();

// Step 5: Dependency re-resolve
run('npm install', true);
checkState();

// Step 6: Static asset regeneration
run('npm run build', true);
checkState();

console.error('Failed to auto-repair. Exiting 1.');
process.exit(1);
