#!/usr/bin/env node

import { execSync } from 'child_process';

function hasDiff() {
  const status = execSync('git status --porcelain').toString().trim();
  return status !== '';
}

function runHealthcheck() {
  try {
    execSync('node scripts/healthcheck.mjs', { stdio: 'pipe' });
    return true;
  } catch (error) {
    return false;
  }
}

function runRepairStep(stepName, command) {
  console.log(`\n--- Running Repair Step: ${stepName} ---`);
  try {
    execSync(command, { stdio: 'inherit' });
  } catch (error) {
    console.error(`Error during ${stepName}, continuing anyway:`, error.message);
  }

  const isHealthy = runHealthcheck();
  const diffExists = hasDiff();

  if (isHealthy && diffExists) {
    console.log(`\nSuccess! System is healthy and a diff was generated by: ${stepName}`);
    process.exit(0);
  } else if (isHealthy && !diffExists) {
    console.log(`System healthy but no diff. Proceeding to next step...`);
  } else {
    console.log(`Healthcheck failed. Proceeding to next step...`);
  }
}

function main() {
  console.log("Starting Self-Heal Pipeline...");

  // Step 1: Rebuild/reinstall (clean install of tooling + deps)
  runRepairStep("Rebuild/Reinstall Dependencies", "npm ci");

  // Step 2: Lint/format auto-fix
  runRepairStep("Lint and Format", "npx eslint --fix src && npx prettier --write .");

  // Step 3: Snapshot/generated updates
  runRepairStep("Update Test Snapshots", "npx vitest run -u");

  // Step 4: Type stubs/analyzer config
  runRepairStep("Update Type Stubs", "npx --yes typesync");

  // Step 5: Dependency re-resolve
  runRepairStep("Dependency Re-resolve", "npm update");

  // Step 6: Static asset regeneration (build)
  runRepairStep("Static Asset Regeneration", "npm run build");

  console.log("\nAll repair steps exhausted.");

  const finalHealth = runHealthcheck();
  const finalDiff = hasDiff();

  if (finalHealth && finalDiff) {
     console.log("System is healthy and diff exists at the end of the pipeline.");
     process.exit(0);
  } else {
     console.error("Failed to self-heal successfully (either still failing healthcheck, or no diff generated).");
     process.exit(1);
  }
}

main();
